### ISSUE TITLE
Cannot Use *

### ISSUE THREAD

**Issue by TheLimePixel** [jaredlll08/RecipeStages#10]
I don't know whether it was a newer forge version (using 14.23.1.260.7) or the latest CraftTweaker version, but something made it so you can't do itemid:* to restrict recipes for multiple items that have the same id, but different meta data any more. It's fixable, but it's annoying.

**Comment by jaredlll08** [comment]
Please show me a script example.

**Comment by TheLimePixel** [comment]
mods.recipestages.Recipes.setRecipeStage("mf", <botania:altar:*>);

 botania:altar is the id for all the different types of Petal Apothecaries, so it should restrict the recipe for all of them, but it restricts it for neither one of them.

**Comment by jaredlll08** [comment]
fixed in dev
