### ISSUE TITLE
Autocrafting isnt possible with other mods except AE2

### ISSUE THREAD

**Issue by Raetac** [jaredlll08/RecipeStages#11]
Hidden/gated recipes cannot be autocrafted via other means except AE2, eg Extra Utilies 2 Mechanical cratfter, FT autocrafter. Basically anything that dosnt directly use vanilla crafting

**Comment by BrewingCoder** [comment]
I came here to report this as well.  Crafting gated recipes, even when stage exists for a user, fails in any mechanical crafting means I've tried.  I have *not* tried AE2 though.   The ones I've tried are:  RFTools Crafter, Refined Storage Crafter, etc.

**Comment by BluMasc** [comment]
still not working in 1.0.8

**Comment by jaredlll08** [comment]
Are you guys setting the stage of the container?
http://crafttweaker.readthedocs.io/en/latest/#Mods/GameStages/RecipeStages/RecipeStages/

**Comment by BluMasc** [comment]
ohh, no.
sorry for the inconvinience

**Comment by Raetac** [comment]
Was a problem I was having in Modern Skyblock 3, as EmosewaPixel is the pack dev, I'm not sure how the stages containers were set

**Comment by jaredlll08** [comment]
just checked the scripts, applied energetics is the only container that he stages, therefore it is the only thing that works...
