### ISSUE TITLE
Recipes restricted with addRecipeStageByMod never show up in JEI

### ISSUE THREAD

**Issue by TheLimePixel** [jaredlll08/RecipeStages#15]
The title is quite self-explanatory; recipes that are restricted with addRecipeStageByMod don't show up in JEI after they are unlocked.

**Comment by jaredlll08** [comment]
Yea... I'm going to need more info.

**Comment by TheLimePixel** [comment]
Here's an example:
I have mods.recipestages.Recipes.setRecipeStageByMod("em", "enderio");
![image](https://user-images.githubusercontent.com/25333164/38265514-6c272096-3776-11e8-938d-1bd3d606818a.png)
I have the stage unlocked
![image](https://user-images.githubusercontent.com/25333164/38265644-c84a181a-3776-11e8-958d-be2544368965.png)
But recipes for items in the mod are still hidden in JEI.

**Comment by jaredlll08** [comment]
Try any other mod besides ender io, something sane and not an alpha / beta,
like tinkers construct or something

**Comment by TheLimePixel** [comment]
Ender IO was just for the example as I already had searched for it in JEI. It's the same for the 70 other mods I have restricted like that. However, as I previously mentioned, only recipes restricted with addRecipeStageByMod don't show up in JEI, so recipes that I have been individually restricted properly get unhidden.

**Comment by jaredlll08** [comment]
I know I kinda forgot about this, but I just tested it now, and it is working fine, I don't believe I changed anything that would fix this though.

I used:
```zenscript
mods.recipestages.Recipes.setRecipeStageByMod("mod", "cyclicmagic");
```
![image](https://user-images.githubusercontent.com/5553605/63509790-52f33d80-c4dd-11e9-80b5-e3211d197736.png)
