### ISSUE TITLE
recipe stage freeze

### ISSUE THREAD

**Issue by TheNimbleNinja** [jaredlll08/RecipeStages#21]
i have a problem when i get to recipe stage in the initializing mods phase in the part 5 section it just freezes but i think if i dont have any scripts for gamestages it just works normaly i dont know what is causing this problem and i dont know how to fix it. it eventualy gets done with what ever it was doing and continues on with the loading. here is my modpack export so you can look at the problem as well.
[Minecraft Ascention Alpha-sdasd.zip](https://github.com/jaredlll08/RecipeStages/files/2295394/Minecraft.Ascention.Alpha-sdasd.zip)

**Comment by jaredlll08** [comment]
I'm not downloading some random zip file. Give scripts and logs if you want help.

Also depending on how much you're doing, it's going to take longer to load.

**Comment by TheNimbleNinja** [comment]
it doesnt say anything in the logs when it gets to that point it just stops

**Comment by jaredlll08** [comment]
Cool, well since you don't want to even give me the log. I can't do anything.

**Comment by TheNimbleNinja** [comment]
if you want the log ill give it to you
[latest.log](https://github.com/jaredlll08/RecipeStages/files/2295448/latest.log)

**Comment by TheNimbleNinja** [comment]
ill even give you my scripts https://gist.github.com/TheNimbleNinja/9ec3ed39829e2eadb84650563471552a

**Comment by jaredlll08** [comment]
I need the crafttweaker.log file.

**Comment by TheNimbleNinja** [comment]
[crafttweaker.log](https://github.com/jaredlll08/RecipeStages/files/2295459/crafttweaker.log)

**Comment by TheNimbleNinja** [comment]
is the reason its taking forever to load at the freeze because i have staged every mod? and have around 300 mods

**Comment by jaredlll08** [comment]
You're staging an absolute fortune, not only is it causing a huge log file (Java IO isn't the fastest), but it has to loop through each and every item and apply an IAction for each of them. 
Also ontop of that, ZenStages doesn't use the method that I made to fix this exact thing, 

```
//mods.recipestages.Recipes.setRecipeStage(String name, String recipeName);
//This sets the stage of all recipes who's item output's modid is "botania"

mods.recipestages.Recipes.setRecipeStageByMod("one", "botania");
```
which can be found here:
https://crafttweaker.readthedocs.io/en/latest/#Mods/GameStages/RecipeStages/RecipeStages/

**Comment by TheNimbleNinja** [comment]
so what do i do to fix this jared?
or is it in the link you posted?

**Comment by TheNimbleNinja** [comment]
im not a smart boi sorry :(

**Comment by TheNimbleNinja** [comment]
question i think i see what i hAve to do but does it matter that i got item stages also in the same script?

**Comment by TheNimbleNinja** [comment]
@jaredlll08  should i post a issue on zenstages for this problem?

**Comment by jaredlll08** [comment]
If you are adamant on using ZenStages, then you need to report it to their issue tracker, if not, convert your scripts to use the modid specific methods that both Recipestages and ItemStages offer.

However at this point, you already have some scripts, it would probably be less trouble reporting to ZenStages and hoping that they can fix it compared to rewriting your scripts.

**Comment by TheNimbleNinja** [comment]
is the importing thing in zenstages?
in new to gamestages
stuff and i dont quite know what im doing im just copying and pasting code that i see from stuff and editing to to my modpack

**Comment by TheNimbleNinja** [comment]
i dont mind converting my scripts to not use zenstages as in my that far into the scripting of stages i just got the base stuff done

**Comment by TheNimbleNinja** [comment]
also i dont know what to do for the zenstages issue. like what do i put in it to tell them there causing a huge java loading in the way i made my scripts?

**Comment by jaredlll08** [comment]
I don't know much about ZenStages, this has gotten a bit offtopic, if you need help with scripts I suggest your join my discord: http://discord.blamejared.com, someone may be able to help you there, I would appreciate if you stopped replying here, as it is spamming my emails and is a clunky chat method.
