### ISSUE TITLE
Any Way to Disable 'stage: [Stage Name]' in Jei?

### ISSUE THREAD

**Issue by uhmbye** [jaredlll08/RecipeStages#23]
Was wondering if we could get a way to disable the Stage: 'stage name' in JEI ([For example](https://i.gyazo.com/db6db703d414383e669cabaa52a94c63.png))? A config option, or function, or even localization so that way we can either change what it says or remove it entirely would be convenient.

Thanks for your time.

**Comment by jaredlll08** [comment]
No, it is useful to know what stage is needed.

**Comment by uhmbye** [comment]
Well maybe there's some unintended functionality here then. The "stage; {stage name}" doesn't show until after you get the stage. If you don't have the stage, the player still has no idea how to get the stage, unless you have a questbook or advancement that says otherwise. 

For me, disabling this would be nice being that, the way I'm using recipestages is not for the stages themselves but simply to just prevent the users from crafting said item until they get a certain item (a blueprint). The stage needed can be confusing to players being that the concept of stages really aren't present in my pack.

Thanks for the fast reply however, I appreciate it.

**Comment by jaredlll08** [comment]
Maybe I can add something like a Config

**Comment by uhmbye** [comment]
That would be wonderful, thanks so much.
