### ISSUE TITLE
[Suggestion] Regex should be by name, not key

### ISSUE THREAD

**Issue by clubpetey** [jaredlll08/RecipeStages#24]
Discovered this while trying to stage tipped arrows.

It seems that setRecipeStageByRegex looks at the recipe key, not the "name" of the item as returned by /ct names.  This causes a fair amount of confusion.  Using tipped arrows as an example:

The name is: `<minecraft:tipped_arrow>.withTag({Potion: ""minecraft:night_vision""})`

The recipe is: `recipes.addShapeless("minecraft:tippedarrow", null, []); `

There doesn't seem to be separate recipes for the arrows, though I can see them in JEI.  There must be somthing special about how arrows are crafted.  Regardless, by using the value returned by /ct names, it would not only clear up confusion with "tippedarrow" vs. "tipped_arrow" but also allow staging based on the type of potion on the arrow.

**Comment by jaredlll08** [comment]
The regex removal only works *because* it looks at the registry key, no good way to do it on the item name.
