### ISSUE TITLE
Thaumcraft recipes with arcane workbench change to normal workbench when using recipe stages

### ISSUE THREAD

**Issue by mattieboy079** [jaredlll08/RecipeStages#34]
I wanted to stage most of thaumcraft behind a later age in my modpack. But when I do this, most items change to the regular workbench in JEI. If I try to craft the items in the regular workbench they are uncraftable, but they are also uncraftable in the arcane workbench where the recipe was crafted initially. 
I think only the recipes I changed with modTweaker stay in the Arcane Workbench. 

The versions I use are:
forge-14.23.5.2854
RecipeStages-1.1.3
Thaumcraft-1.12.2-6.1.BETA26
ThaumicJEI-1.12.2-1.6.0-27

**Comment by jaredlll08** [comment]
recipe stages is only for normal crafting table recipes.
