### ISSUE TITLE
Regex problems

### ISSUE THREAD

**Issue by wootaboot** [jaredlll08/RecipeStages#35]
mods.recipestages.Recipes.setRecipeStageByRegex("tech_nuclear", "^(?!(nuclearcraft:(tile|item)\.nuclearcraft\.(part\.plate_basic|radiation_badge|rad_shielding\.light|decay_generator))|(crafttweaker:ct_shaped(-972668505|-1212246526|-59823180|1987490634)))");

using the above to add stages to all but the listed items.

I'm getting this error, stanhebben.zenscript.parser.TokenException: Invalid character at Stages.zs:547 - .
no idea what is causing it

**Comment by wootaboot** [comment]
I figured out why i was giving me invalid character as well as found out that this wont work due to the fact that it doesnt go through every recipe to find the ones that match this. 

error was having \ in from of . which is standard but doesnt work in CT.

**Comment by jaredlll08** [comment]
post your script on pastebin

**Comment by wootaboot** [comment]
i gave up and just manually input all the entries...
