### ISSUE TITLE
[1.12.2] Bug with AE2

### ISSUE THREAD

**Issue by vizthex123** [jaredlll08/RecipeStages#36]
Whenever I try to craft something in an AE2 crafting terminal and it has a game stage (I have the stage unlocked), it doesn't let me craft it.

Crafting the item in a regular crafting table works fine though.

**Comment by jaredlll08** [comment]
You need to set the stage of the container. (as in, the AE container does not care what stage the player has, it only cares about what has been assigned to it)

**Comment by vizthex123** [comment]
What do you mean by that? The item and player have the same stages, so it should work.

Isn't that what determines if it works or not for regular crafting tables?

**Comment by jaredlll08** [comment]
AE isn't a regular crafting table.

**Comment by vizthex123** [comment]
Ah ok. Of course they use their own API, ah well.
