### ISSUE TITLE
"Error running action" setting game stages

### ISSUE THREAD

**Issue by ghost** [jaredlll08/RecipeStages#37]
Hello I haven't been able to do a good test on whether recipes that seem to error end up having their gamestages stage set, but I get several errors when GameStages processes my scripts in crafttweaker.log

`java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER`

CraftTweaker.Log: https://pastebin.com/EGY5bV7g

One of the scripts for setting stages by mod: https://pastebin.com/K4MBtiyE

Let me know if there are any other questions.

**Comment by ghost** [comment]
Seems to only occur when setting the following mods:

mekanism, mekanismtools, mekanismadditions, mekanismgenerators, and silentgear

**Comment by TechniumUnlimited** [comment]
I think this is expecting a serverplayerentity but getting a client one? https://github.com/jaredlll08/RecipeStages/blob/28ef9c8d617d23f2cbaba3c7736310fae3403974/src/main/java/com/blamejared/recipestages/recipes/RecipeStage.java#L79
