### ISSUE TITLE
use of damagable items in recipes

### ISSUE THREAD

**Issue by deicide-wil** [jaredlll08/RecipeStages#39]
the `.reuse()` and `.transformDamage()` methods does not work with recipe stages,
for both `mods.recipestages.Recipes.addShapeless()` or `mods.recipestages.Recipes.setRecipeStage()`

[https://pastebin.com/MeeHDTeP](url)
(see bottom of code)

**Comment by jaredlll08** [comment]
Crafttweaker log please

**Comment by deicide-wil** [comment]
This is the crafttweakerlog:
[https://pastebin.com/UCf2ECjZ](https://pastebin.com/UCf2ECjZ)

Test code used for this log:
[https://pastebin.com/XddNESWA](https://pastebin.com/XddNESWA)

Attached full log:
[crafttweaker.log](https://github.com/jaredlll08/RecipeStages/files/5857913/crafttweaker.log)

**Comment by deicide-wil** [comment]
theres no crashes, but the tool item used in the recipe disappears after crafting.
it should be left in the crafting grid with durability consumed a bit (if used the `craftingTable.addShapeless()` method and no recipe stages added)

**Comment by jaredlll08** [comment]
Thanks for the report! This one totally missed my testing, should all be fixed now :)
