### ISSUE TITLE
1.12.2: Alters Standard Recipes

### ISSUE THREAD

**Issue by jelaw21** [jaredlll08/RecipeStages#4]
I was testing this mod and I added two recipes to two stages with the following code:

mods.recipestages.Recipes.setRecipeStage("newb", "minecraft:wooden_hoe");
mods.recipestages.Recipes.setRecipeStage("newber", "minecraft:stone_hoe");

![image](https://user-images.githubusercontent.com/21100827/33394052-1b47d8e2-d50f-11e7-956a-de77874bd97b.png)

The image shows how the recipes for the wooden hoe is display with both the Minecraft crafting book and the JEI. Same for stone hoe. The JEI says its now a shapeless recipe. However, the mechanics of the mod still work. I can't craft the hoe, with the correct recipe, until I change my stage.

**Comment by jaredlll08** [comment]
What version?

**Comment by jelaw21** [comment]
1.12.2

**Comment by jaredlll08** [comment]
I know. What mod version?

**Comment by jelaw21** [comment]
1.0.0

**Comment by jaredlll08** [comment]
It's been fixed indev.

**Comment by jelaw21** [comment]
Will there be a new release or should I re-install?
