### ISSUE TITLE
incompatible with Tinker Construct

### ISSUE THREAD

**Issue by Diversion98** [jaredlll08/RecipeStages#46]
**Issue description:**
When I progress to a new stage, mods will unlock thanks to gamestages and recipestages.
We cant craft things with the Tinkers Construct crafting station after we unlocked a mod through a stage.

the workbench from vanilla and the crafting station from the crafting station mod works perfectly.

if you comment the following code in the script with //, it will work again.
mods.recipestages.Recipes.setRecipeStageByMod("stage1", "minecraft");

I also made an issue on Tinkers construct page:
https://github.com/SlimeKnights/TinkersConstruct/issues/4446

If you need more information, i'm happy to provide.
Don't know what u need.

**How to reproduce:**

1. Go to config -> gamestages and edit known_stages.json to add ["stage1"]

2. Make a Zenscipt file and include this code in it:
   mods.recipestages.Recipes.setRecipeStageByMod("stage1", "minecraft");

3. Make a new world and give yourself stage 1 with the command "/gamestage add playername stage1"

4. Try to craft something from elemental craft in the crafting station from tinkers construct.

**Mods + versions:**
Forge 36.1.16
Bookshelf 10.0.7
CraftTweaker 7.1.0.278
Game Stages 7.1.2
Just Enough Items 7.6.4.90
Mantle 1.6.92
Recipe Stages 2.0.0.14
Tinkers Construct 3.0.3.144

**Comment by Diversion98** [comment]
After we did some testing, we also have issues with refined storage.
Gonna see tommorow if it's the same problem like tinkers. (Can't test it right now)

**Comment by jaredlll08** [comment]
The ***EXACT*** same issue as described here?
https://github.com/SlimeKnights/TinkersConstruct/issues/4446#issuecomment-838845150

**Comment by Diversion98** [comment]
Yes the EXACT same.

Well almost, I said something about the shift clicking. With the refined storage mod, that bug is not there. Maybe another bug?

**Comment by jaredlll08** [comment]
Unable to reproduce with refined storage using the script:
```less
mods.recipestages.Recipes.setRecipeStageByMod("stage1", "minecraft");
mods.recipestages.Recipes.setPrintContainers(true);
mods.recipestages.Recipes.setContainerStages("com.refinedmods.refinedstorage.apiimpl.network.node.GridNetworkNode$1", ["stage1"]);


```
crafting works completely fine, no ghost item is shown like it is with tinkers

**Comment by jaredlll08** [comment]
I believe this to be on Tinkers Construct side. I am updating the linked issue with my findings.
