### ISSUE TITLE
RecipeAction Not Triggered

### ISSUE THREAD

**Issue by lunareclipse-64** [jaredlll08/RecipeStages#50]
My scripts**(There's no error in crafttweaker.log)**:
`Recipes.addShapeless("stagename",<minecraft:potion>.withTag({Potion: "minecraft:water"}), 
[<contenttweaker:item>.transformReplace(<contenttweaker:anotheritem>),<minecraft:glass_bottle>] as IIngredient[],
    null,
    function(out,cInfo,player){
	player.give(<botany:misc:5>);
        print("THAT'S GROSS!");
    }
);`
But when I perform this recipe in game, neither <botany:misc:5> was given to me, nor "THAT'S GROSS!" appeared in the log.
Maybe there's something wrong with my scripts(those items really exist), or with RecipsStages?

**Comment by jaredlll08** [comment]
Mc version?

**Comment by lunareclipse-64** [comment]
> Mc version?

Minecraft 1.12.2
Crafttweaker 4.1.20.655
RecipsStages 1.1.3.7
