### ISSUE TITLE
Toms Simple Storage Mod

### ISSUE THREAD

**Issue by spdkils** [jaredlll08/RecipeStages#54]
Stages do not work with this mod, however it does work with pretty pipes storage mod. Not sure why/how the hooks work.

**Comment by jaredlll08** [comment]
Define doesn't work.

Are there errors in the log?
Have you tried staging the container?

**Comment by spdkils** [comment]
Recipes behind the stage, are shown, and create a phantom item, but when you try and craft nothing pops out.
So, this mod has a crafting terminal, and it looks like it implements the normal crafting bench stuff... 

https://github.com/tom5454/Toms-Storage/blob/master/src/main/java/com/tom/storagemod/gui/GuiCraftingTerminal.java

However you can't craft staged recipes with it

**Comment by spdkils** [comment]
Not to add on too much, but it's the same behavior with the sophisticated backpacks integrated crafting bag

**Comment by jaredlll08** [comment]
If you aren't getting any errors, that means that it *should* support Container staging.
https://docs.blamejared.com/1.16/en/mods/RecipeStages/RecipeStages#packages-and-containers

**Comment by spdkils** [comment]
So I'm confused, if I give a terminal a stage, does that terminal forever act at that stage, or does it's stage now reflect the user of that terminal?

**Comment by jaredlll08** [comment]
It forever has the stage.

If we don't have a player, we can't possibly know what stage a player has to tell the terminal so it can do things correctly.

**Comment by spdkils** [comment]
Well thanks for the info, I was able to get the terminal to craft that stage. Now the question becomes, why does a normal crafting table work, restricted by player, and one in a mod does not?

**Comment by jaredlll08** [comment]
If the inventory gives us a player, we can work with it, simple as that, it doesn't even need to be a normal vanilla table, just needs to give us the player.

Although in cases like this, and AE2 / RF auto crafters, you simple don't have a player at all, so the package / container stuff was added so at-least there is *some* support.
