### ISSUE TITLE
1.18.1 Please

### ISSUE THREAD

**Issue by blood789** [jaredlll08/RecipeStages#56]
Hello, When to update to 1.18.1 ? 
Thanks.

**Comment by jaredlll08** [comment]
Not sure why you closed it, I had been waiting for Gamestages to port (which it only did the other day), since this mod requires it.

**Comment by blood789** [comment]
en.....
Because there are too many issues in my github, and no reply for several months, so I close some issues....
Thanks for your work.

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/RecipeStages/commit/082645784dc564f5551a2f0dde0840ce7560b438
