### ISSUE TITLE
1.16.5 Suggestion 

### ISSUE THREAD

**Issue by Subthy** [jaredlll08/RecipeStages#57]
Hello,

It would be cool if you were able to lock a tag, cause that would save a lot of time and lower the amount of restriction and thus improving performance.  You can do that with Item Stages, so why wouldn't you be able to do that with Recipe Stages.

**Comment by jaredlll08** [comment]
You should already be able to do this.

```zenscript
mods.recipestages.Recipes.setRecipeStage("stage", <tag:items:minecraft:wool>.asIIngredient());
```
