### ISSUE TITLE
[QUESTION] How to only show recipes player can craft?

### ISSUE THREAD

**Issue by BelgianDev** [jaredlll08/RecipeStages#59]
Hello I want to show only recipes that you can craft at that stage in JEI how can I do that?

Thanks Raft

**Comment by jaredlll08** [comment]
I am not following, the recipes say what stage they require (if you have the stage unlocked)

**Comment by BelgianDev** [comment]
But if i do so i will need to reload the game to show the crafts of that stage

**Comment by jaredlll08** [comment]
When you unlock a stage, the recipes are automatically added to JEI, you don't need to reload anything.

**Comment by BelgianDev** [comment]
Sorry i don't realy understand when i add a recipes to a stage and i don't have that stage there still showed in JEI

**Comment by jaredlll08** [comment]
If you are talking about during modpack development, like you editing scripts making your modpack, then depending on your game version:
1.12: Required to restart the game for scripts to rerun, no way around this.
1.16+: a simple `/reload` will reload scripts and the recipes will show as staged in JEI.

What mc version are you using and what are you trying to do?

**Comment by BelgianDev** [comment]
1.18.2 
I'm trying to hide items in JEI that you can't craft

**Comment by jaredlll08** [comment]
RecipeStages only deals with hiding recipes, which it does automatically.

If you want to hide items from the item list, then you need ItemStages which does that.

If that is what you want, then I'm going to be closing this issue as it doesn't relate to this mod.

**Comment by BelgianDev** [comment]
I see, thanks for the support

**Comment by BelgianDev** [comment]
I'm gonna check ItemStage thanks
