### ISSUE TITLE
[1.12.2] Shaped Recipe Displaying As Shapeless?

### ISSUE THREAD

**Issue by TheLimePixel** [jaredlll08/RecipeStages#6]
So basically, this is the recipe for the Pulse Piston from FactoryTech that's displayed in JEI without adding a stage to it:
![image](https://user-images.githubusercontent.com/25333164/34603305-be9ae334-f203-11e7-9c45-56f5f485c2f6.png)
And it obviously works
![image](https://user-images.githubusercontent.com/25333164/34603359-edfaafe2-f203-11e7-8995-0024b8bda155.png)

 This is the recipe displayed in JEI once a stage is added to it:
![image](https://user-images.githubusercontent.com/25333164/34603376-ff251bae-f203-11e7-8c3c-5451d2309afb.png)
 And it does not work
![image](https://user-images.githubusercontent.com/25333164/34603398-15198b52-f204-11e7-95a4-4029ff4eadec.png)

**Comment by TheLimePixel** [comment]
Actually, after further observation, all Shaped recipes seem to get displayed as Shapeless after they have a stage added to them.
![image](https://user-images.githubusercontent.com/25333164/34605765-0ddb2126-f20d-11e7-8269-9f97204a7981.png)
![image](https://user-images.githubusercontent.com/25333164/34605797-2db8cb88-f20d-11e7-81f8-49b2d89cf3d8.png)

**Comment by jaredlll08** [comment]
already fixed in dev, just released on curse

**Comment by justinrusso** [comment]
This popped up again in 1.0.6. `setRecipeStage()` caused the recipe to appear shapeless.

JEI shows the Spindle recipe like
![2018-01-14_20 55 47](https://user-images.githubusercontent.com/13619922/34919486-ba611a42-f96d-11e7-9f18-2c4aee2cb5fc.png)

But that doesn't work and it actually is like
![2018-01-14_20 55 57](https://user-images.githubusercontent.com/13619922/34919497-ceee1bc2-f96d-11e7-969e-6581c9b366fc.png)
