### ISSUE TITLE
SophisticatedBackpacks, RecipeStages and DYE Recipe

### ISSUE THREAD

**Issue by mfventura** [jaredlll08/RecipeStages#61]
Hello, I have an issue that i cant resolve.

With the mod SophisticatedBackpacks. -> https://github.com/P3pp3rF1y/SophisticatedBackpacks
And the following script:
`
mods.recipestages.Recipes.setRecipeStageByMod("backpacks-all", "sophisticatedbackpacks");
mods.recipestages.Recipes.setRecipeStage("backpack-t1", <item:sophisticatedbackpacks:backpack>);
`

I can't DYE the basic backpack when I have the stage backpack-t1
The coloured backpack item has the same name than the basic, changes are NBT tags.

How can I solve this?

**Comment by jaredlll08** [comment]
If you have both stages does it work as intended?

**Comment by mfventura** [comment]
Hello, sorry i didnt had internet on the weekend.
Yes, with both stages it works, it's not a fail of the mod ^^'

**Comment by jaredlll08** [comment]
Giving a single recipe two stages isn't supported, it is meant to be a single stage per recipe.

It working fine with both stages is technically a bug, it should complain about being staged twice instead.
