### ISSUE TITLE
Occultism crafting grid JEI integration does not work with staged recipes

### ISSUE THREAD

**Issue by Saereth** [jaredlll08/RecipeStages#63]
![image](https://user-images.githubusercontent.com/9200909/190230881-a5f8b973-72a4-479e-8289-e4f78bf98eca.png)

Im not sure which mod would need to fix that or if it's even possible, so I'm reporting to both but basically the jei crafting integration does not work with occultism if it's a staged recipe even if the recipe stage is unlocked

https://github.com/klikli-dev/occultism/issues/787

**Comment by jaredlll08** [comment]
I don't know anything about occultism so I am not sure how their crafting grid actually works, but just to confirm, the transfer handler works fine on other modded tables?

**Comment by Saereth** [comment]
it does yeah and I can manually add the items to the occultism crafting grid and it will work just the transfer handler doesnt work with occultism specifically, so looks like an issue on their end you think?

**Comment by klikli-dev** [comment]
Creator of occultism here! I haven't encountered RecipeStages before hence I don't know much.
What I can say is, I've got a custom trasnfer handler for my storage controller to ensure that the recipe uses the items that are available in the highest amounts in case multiple items fit a recipe

**Comment by jaredlll08** [comment]
Sorry this took so long to get to, but it should be fixed now!
