### ISSUE TITLE
create is creating automated mixing recipes allowing to bi pass staged mods or recipes

### ISSUE THREAD

**Issue by Ajw2003** [jaredlll08/RecipeStages#65]
create is creating automated mixing recipes allowing to bi-pass staged mods or recipes, the title essentially explains the issue. when trying to stage a mod using its modid i.e (mods.recipestages.Recipes.setRecipeStageByMod("botany", "botania");) the create mod reads this as a recipe that has been created and adds it as an automated shapeless crafting recipe using the mixer.

not sure if this problem is on their end or this mods end but figured I'd start somewhere

**Comment by jaredlll08** [comment]
As far as I am aware, I can't control what recipes they create, so not sure the best way to fix this, I also imagine they would run into a bunch more issues like mods that have experience crafting or similar.
