### ISSUE TITLE
A port to 1.19.2

### ISSUE THREAD

**Issue by ManaStar** [jaredlll08/RecipeStages#66]
Was migrating a pack of mine to 1.19.2 and saw this wasn't updated, am not normally the person begging for ports by any means but it would be greatly appreciated if you'd please consider this! I do believe that Game Stages is also up to date so this should be possible, surely!

**Comment by malice936** [comment]
Seconding this request, this is literally the only mod that allows for gated crafting, and gated crafting is an absolute must for a pack I'm currently building.

**Comment by jaredlll08** [comment]
fixed by https://github.com/jaredlll08/RecipeStages/commit/efdeccdd9e7da95fda5899a0f916afb6f568824e
