### ISSUE TITLE
The mod with create's mechanical crafter have a bug

### ISSUE THREAD

**Issue by wumengzhixing** [jaredlll08/RecipeStages#67]
Forge：40.1.84
version 1.18.2
RecipeStages-3.0.0.10
create-1.18.2-0.5.0.e
In my modpack, the items that are locked by Recipe Stages, although unlocked stages, can be synthesized in vanilla craftingtable, but cannot be synthesized by create's mechanical crafter. Can you solve this problem?I would appreciate it.
![`XD`@1ZOV458WD@X 7WOQO5](https://user-images.githubusercontent.com/88496786/208889366-3a3ca123-35d8-418d-b89f-1b7e031df8d9.JPG)
![QC81Z2LA 88`9V2BF4XB@HO](https://user-images.githubusercontent.com/88496786/208889377-885ca6f3-0dcf-4301-8768-07c42c625245.JPG)
![X2N 3ARAP%CW5N6K56SL{HP](https://user-images.githubusercontent.com/88496786/208889381-d52f350d-8d91-4f6e-9b35-c6973752f5b1.JPG)
![FKM%FI(8 HRH_I4(78HJ) H](https://user-images.githubusercontent.com/88496786/208889384-0afea5b1-a76a-4d34-9b5f-893ead801ce8.JPG)

**Comment by jaredlll08** [comment]
You can try to use https://docs.blamejared.com/1.18/en/mods/RecipeStages/RecipeStages#packages-and-containers to give the crafter a stage, however there is no solution in which it can use the stage of the player.
