### ISSUE TITLE
Can't craft items from GameStages in custom workbenches

### ISSUE THREAD

**Issue by Proxwian** [jaredlll08/RecipeStages#68]
Example: Workbench in Sophisticated Backpacks upgrade and QIO System from Immersive Engineering

![image](https://user-images.githubusercontent.com/31781674/211041316-fe18f066-dfd3-4bd7-9048-25a95060a26e.png)
![image](https://user-images.githubusercontent.com/31781674/211041372-ee9ba169-ffe6-4011-9b9f-c2a259de88c4.png)
![image](https://user-images.githubusercontent.com/31781674/211041443-5e681b9c-91fe-45ca-9ee8-7a7760de5ac2.png)

**Comment by Proxwian** [comment]
Also I found this https://docs.blamejared.com/1.18/en/mods/RecipeStages/RecipeStages#packages-and-containers, but it seems to be strange that I must write every modded container by myself to work with mod

**Comment by Proxwian** [comment]
Also when I tried to craft in these interfaces, I can't get logs from RecipeStages about their containers
![image](https://user-images.githubusercontent.com/31781674/211044311-7775bc7e-efde-4cb5-b7d1-95e6b2f94047.png)

**Comment by jaredlll08** [comment]
What mod adds the workbench? I don't see anything about it in the sophisticated backpacks code.

Also immersive engineering does not have a QIO system. 

Please tell me the correct mods so I know what I'm meant to be looking at.

**Comment by Proxwian** [comment]
Sorry, not IE, it's Mekanism

**Comment by jaredlll08** [comment]
and the workbench?

**Comment by Proxwian** [comment]
Portable QIO Dashboard from Mekanism
Workbench (Crafting) Backpack Upgrade from SophisticatedBackpacks

**Comment by Proxwian** [comment]
If that need to be mentioned, I've set recipe stages by mod like this
![image](https://user-images.githubusercontent.com/31781674/211045900-05b5dc8b-2332-4ced-9918-b57419aeff52.png)

**Comment by jaredlll08** [comment]
Okay so, for Sophisticated Backpacks, they don't pass a player in, so we do not have a player to get the stage from, there is no solution to this, there simply just isn't a player so you need to use:
https://docs.blamejared.com/1.18/en/mods/RecipeStages/RecipeStages#packages-and-containers

As for Mekanism, the same situation goes on, I have been in contact with the mekanism developer and we came up with a way to get something working, but you should be able to use packages and containers to "fix" it in the mean time.

**Comment by Proxwian** [comment]
![image](https://user-images.githubusercontent.com/31781674/211059464-02b22aa1-821a-42f1-a2b4-af5fc1628429.png)
I've already tried this and that doesn't help at all

**Comment by jaredlll08** [comment]
Those are not the correct package names.

The package names for sophisticated backpacks are:
```
net.p3pp3rf1y.sophisticatedcore
net.p3pp3rf1y.sophisticatedbackpacks
```

They should be printed when you try and craft the recipe in the interfaces. (if you have `mods.recipestages.Recipes.setPrintContainers(true);`)


If they aren't printed, then you can't stage the package and there is nothing that can be done to solve the issue.

**Comment by Proxwian** [comment]
It's not working, same for Mekanism. Hope this can be fixed with help of Mekanism developer

**Comment by jaredlll08** [comment]
I just loaded sophisticated backpacks using the following script:
```zenscript
mods.recipestages.Recipes.setRecipeStage("hoe", <item:minecraft:stone_hoe>);
mods.recipestages.Recipes.setPrintContainers(true);
```

I can confirm that the backpack can't craft the hoe, however in the log file, it **does** print:
```
[13:12:27.043][INFO]: Tried to craft a recipe in container: 'net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingItemHandler$1'
```


If I add:
```zenscript
mods.recipestages.Recipes.setPackageStages("net.p3pp3rf1y", "hoe");
```
to my script file, I can now craft the hoe in the crafting upgrade (regardless of if I have the stage or not).

As I mentioned, sohpisticated backpacks doesn't provide a player, so this is the only solution to the problem.

As for Mekanism, I am working with the Mekanism dev to make it work, however it will most likely only be for 1.19 unless she wants to make a 1.18 release in the future.
