### ISSUE TITLE
Forking and setting up development environment

### ISSUE THREAD

**Issue by BlueAsclepias** [jaredlll08/RecipeStages#69]
I've been trying to set up the environment to properly build a fork of this project on branch 1.16, however it seems like there are some problems with gradle.
From the get go, using gradle 4.10.3 and JDK 1.8, I get the following error when trying to build:

```
A problem occurred configuring root project 'RecipeStages'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find Schoomp.jar (com.diluv.schoomp:Schoomp:2.1.0+0).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/com/diluv/schoomp/Schoomp/2.1.0+0/Schoomp-2.1.0+0.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I've looked up Schoomp and found out that this version 2.1.0 seems to be incorrect as the lastest version is 1.2.6. This is a ModTemplate dependency however. 

I'm kind of new to using gradle and modding minecraft in general, have I done something wrong or is this branch currently broken, or perhaps something else?

**Comment by jaredlll08** [comment]
The version of schoomp it is looking for was a privately hosted custom version that I was using to test, it no longer exists and I usually deal with these errors as I come across them (updating to new versions and the like).

If you don't mind me asking, why do you want to fork? I still accept PRs and occasionally do bug fixes / feature requests myself on older minecraft versions, so if there was a feature you would like or a bug you need fixing, it can most likely be put into the main repo.

**Comment by BlueAsclepias** [comment]
I am creating a personal modpack that requires stages to be set on recipes for different working stations other than the crafting table, these include Smithing Table recipes and custom stations from [SewingKit](https://github.com/gigaherz/SewingKit), [Farmer's Delight](https://github.com/vectorwing/FarmersDelight) and some other mods.
After reading the documentation, I found that RecipeStages only allow stages to be set on Crafting Table recipes and add stages to an entire working station, so I decided to fork RecipeStages to see if I could add a new function for these mods in particular.

**Comment by jaredlll08** [comment]
Update modtemplate to `2.+` and it should solve the issue.

If you do get those working, a PR would be appreciated

**Comment by BlueAsclepias** [comment]
Will do. thank you!
It worked. After changing ModTemplate version to 1.0.0.22 (other versions above this seems to have issues with this branch) and commenting out the refinedstorage dependency on line 110 (doesn't seem to be used anywhere and the repo url is unavailable).
