### ISSUE TITLE
[Suggestion] JEI - Custom recipe wrapper API

### ISSUE THREAD

**Issue by GoryMoon** [jaredlll08/RecipeStages#7]
I wondered if it would be possible to add a way so you can add custom handlers to recipes that are staged.
For example I have added a JEI recipe wrapper for a dynamic recipe in The Betweenlands and if you stage it, the recipe it self works correctly with staging but the JEI handler don't show it anymore even when having that stage.
Maybe add an API for mods to add a custom wrapper for recipes or something?

**Comment by jaredlll08** [comment]
It isn't really possible as I need to actually build the recipe wrapper, which isn't too easy to do
