### ISSUE TITLE
[1.20.1]No errors when entering the game main menu, but unable to enter the world

### ISSUE THREAD

**Issue by LILPRINCES** [jaredlll08/RecipeStages#74]
log: https://mclo.gs/i7tIu74

**Comment by ColdTearsYY** [comment]
same error. Maybe both of us didn't install jei on our client. But how could that crash?

**Comment by LILPRINCES** [comment]
> 同样的错误。也许我们都没有在客户身上安装jei。但是那怎么会崩溃呢？

装jei能进吗？我是试了一大堆mod进不了才试没有mod之后也不能进的。如果你会看崩溃报告的话...

**Comment by jaredlll08** [comment]
I've fixed the crash if JEI isn't working.

**Comment by LILPRINCES** [comment]
> I've fixed the crash if JEI isn't working.

thank you bro
